/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --strict-vars=false worker/worker-configuration.d.ts` (hash: 07f8702fcd412f5ac18605445f96262c)
interface __BaseEnv_Env {
	AVALA_MCP_WORKER_ENABLED: string;
	AVALA_MCP_ROUTING_MODE: string;
	AVALA_MCP_AWS_ORIGIN_ROUTE_URL: string;
	AVALA_BASE_URL: string;
	AVALA_MCP_OAUTH_RESOURCE: string;
	AVALA_MCP_OAUTH_ISSUER: string;
	AVALA_MCP_OAUTH_API_AUDIENCE: string;
	AVALA_MCP_OAUTH_CLIENT_ID: string;
	AVALA_MCP_OAUTH_SCOPES: string;
	AVALA_MCP_BUILD_SHA: string;
	AVALA_MCP_RELEASE_TAG: string;
	ALLOWED_ORIGINS: string;
	AVALA_MCP_INTERNAL_CLIENT_SECRET: string;
	AVALA_MCP_OAUTH_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AVALA_MCP_WORKER_ENABLED" | "AVALA_MCP_ROUTING_MODE" | "AVALA_MCP_AWS_ORIGIN_ROUTE_URL" | "AVALA_BASE_URL" | "AVALA_MCP_OAUTH_RESOURCE" | "AVALA_MCP_OAUTH_ISSUER" | "AVALA_MCP_OAUTH_API_AUDIENCE" | "AVALA_MCP_OAUTH_CLIENT_ID" | "AVALA_MCP_OAUTH_SCOPES" | "AVALA_MCP_BUILD_SHA" | "AVALA_MCP_RELEASE_TAG" | "ALLOWED_ORIGINS" | "AVALA_MCP_INTERNAL_CLIENT_SECRET" | "AVALA_MCP_OAUTH_CLIENT_SECRET">> {}
}
